#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
error Meh...
#endif

// GO(lua_pushfstring,
GO(luaL_typerror, iFpip)
GO(luaL_register, vFppp)
GO(lua_getfield, iFpip)
// GO(lua_pushvfstring,
GO(luaL_pushmodule, vFppi)
GO(luaL_pushresult, vFp)
// GO(luaopen_io,
GO(lua_xmove, vFppi)
GO(lua_pushthread, iFp)
// GO(luaL_openlib,
GO(luaL_addlstring, vFppL)
GO(lua_resume, iFppip)
GO(luaL_optnumber, dFpid)
GO(lua_setfield, vFpip)
// GO(luaopen_math,
GO(lua_newuserdata, pFpL)
// GO(luaJIT_profile_stop,
GO(lua_gettable, iFpi)
GO(lua_gethookcount, iFp)
GO(lua_settop, vFpi)
GO(lua_rawequal, iFpii)
GO(lua_pushstring, pFpp)
GO(luaL_execresult, iFpi)
// GO(lua_dump, iFp
GO(luaL_where, iFpi)
GO(lua_error, iFp)
// GO(luaopen_string_buffer,
// GO(luaopen_ffi,
GO(lua_settable, vFpi)
GO(luaL_loadfilex, iFppp)
GO(lua_getinfo, iFppp)
GO(lua_isnumber, iFpi)
// GO(luaopen_base,
// GO(lua_equal,
// GO(lua_upvalueid,
// GO(lua_sethook,
// GO(lua_next,
GO(luaL_checklstring, pFpip)
GO(lua_topointer, pFpi)
GO(lua_tothread, pFpi)
// GO(lua_gc,
GO(lua_createtable, vFpii)
// GO(luaopen_jit,
// GO(lua_setfenv,
GO(lua_pcall, iFpiii)
GO(luaL_unref, vFpii)
GO(lua_call, vFpii)
GO(luaL_testudata, vFpip)
GO(lua_type, iFpi)
GO(luaL_newmetatable, iFpp)
GO(lua_concat, vFpi)
GO(lua_gethookmask, iFp)
// GO(lua_lessthan,
// GO(lua_tocfunction,
GO(luaL_loadbuffer, iFppLp)
GO(lua_getmetatable, iFpi)
GO(luaL_loadstring, iFpp)
// GO(luaopen_package,
GOM(lua_pushcclosure, vFEppi)
GO(luaL_checkudata, pFpip)
// GO(lua_gethook,
// GO(lua_newstate,
GO(lua_getupvalue, pFpii)
GO(luaL_optlstring, pFpipp)
GO(luaJIT_setmode, iFpii)
GO(luaL_newstate, pFv)
GO(lua_pushnil, vFp)
GO(luaL_gsub, pFpppp)
// GO(lua_getfenv,
// GO(luaL_findtable,
GO(lua_objlen, LFpi)
GO(lua_remove, vFpi)
GO(lua_rawseti, vFpiL)
GO(lua_close, vFp)
GO(lua_pushlightuserdata, vFpp)
GO(luaL_addstring, vFpp)
GO(luaL_checkinteger, lFpi)
GO(lua_rawset, vFpi)
GO(luaL_loadbufferx, iFppLpp)
GO(luaL_checknumber, dFpi)
// GO(luaopen_table,
GO(lua_rawgeti, iFpil)
// GO(luaopen_string,
GO(luaL_loadfile, iFpp)
GO(luaL_addvalue, vFp)
GO(lua_setupvalue, pFpii)
// GO(luaopen_os,
GO(luaL_setfuncs, vFppi)
GO(luaL_setmetatable, vFpp)
GO(luaL_callmeta, iFpip)
GO(lua_gettop, iFp)
GO(lua_replace, vFpi)
GO(luaL_prepbuffer, pFp)
// GO(lua_cpcall,
GO(lua_getlocal, pFppi)
GO(lua_pushvalue, vFpi)
GO(luaL_traceback, vFpppi)
GO(lua_tonumberx, dFpip)
GO(lua_pushnumber, vFpd)
GO(luaL_ref, iFpi)
GO(lua_newthread, pFp)
GO(lua_isstring, iFpi)
GO(lua_iscfunction, iFpi)
GO(lua_touserdata, pFpi)
GO(lua_isyieldable, iFp)
GO(lua_tolstring, pFpip)
GO(lua_setlocal, pFppi)
GO(luaL_checkany, vFpi)
GO(lua_checkstack, iFpi)
// GO(lua_getallocf,
GO(luaL_optinteger, lFpil)
GO(luaL_checktype, vFpii)
GO(lua_version, dFp)
// GO(luaopen_bit,
GO(lua_rawget, iFpi)
GO(lua_copy, vFpii)
// GO(lua_load,
GO(luaL_checkstack, vFpip)
GO(lua_pushlstring, pFppL)
GO(lua_toboolean, iFpi)
// GO(lua_insert,
GO(lua_tointegerx, lFpip)
// GO(luaL_checkoption,
// GO(luaL_fileresult,
// GO(luaopen_debug,
// GO(luaJIT_profile_start,
GO(lua_tonumber, dFpi)
GO(lua_typename, pFpi)
GO(luaL_buffinit, vFpp)
// GO(luaJIT_profile_dumpstack,
GO(lua_tointeger, lFpi)
// GO(luaL_error,
GO(lua_pushboolean, vFpi)
GO(lua_status, iFp)
// GO(lua_yield,
GO(luaL_openlibs, vFp)
GO(luaL_getmetafield, iFpip)
GO(lua_upvaluejoin, vFpiiii)
// GO(lua_setallocf,
GO(lua_setmetatable, iFpi)
// GO(lua_loadx,
GO(lua_isuserdata, iFpi)
GO(lua_pushinteger, vFpl)
GO(lua_getstack, iFpip)
GO(luaL_argerror, iFpip)
GO(lua_atpanic, pFpp) // TODO
